version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean assembly:assembly -DdescriptorId=jar-with-dependencies package
artifacts:
  files:
    - target/alexa-intent-tester-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes