version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn assembly:assembly -DdescriptorId=jar-with-dependencies 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/alexa-intent-tester-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes